### ISSUE TITLE
Hi dear developer, could you please write a detailed deployment tutorial?

### ISSUE THREAD

**Issue by WlpZ** [MNThomson/containerflare#32]
I forked your code repository and deployed it to Cloudflare pages. The web page can open normally, but when I ran Docker run xx.mywebsite.xx/hello-world, I received the following prompt: Docker: Error response from day: unknown: No Data
![Uploading 500.png…]()

**Comment by Links17** [comment]
Hi, I'm having this problem too, have you solved it yet?

**Comment by MNThomson** [comment]
Whoops, I totally missed this the first time around.

I just added the https://github.com/MNThomson/containerflare/blob/master/dev/upload.sh script in 1ccf3bb which will push the local data to a remote KV/R2 storage. You will have to hit the `/v2/seed` api first so as to download the blobs locally, at which point you can then configure and run `upload.sh`.
